Revert "Fix some mypy errors"
Python in R4.1's dom0 is too old for some of those constructs:

    Traceback (most recent call last):
      File "/usr/bin/qrexec-policy-daemon", line 2, in <module>
        from qrexec.tools.qrexec_policy_daemon import main
      File "/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_daemon.py", line 29, in <module>
        from .qrexec_policy_exec import handle_request
      File "/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_exec.py", line 31, in <module>
        from ..policy import parser
      File "/usr/lib/python3.8/site-packages/qrexec/policy/parser.py", line 188, in <module>
        class VMTokenMeta(abc.ABCMeta):
      File "/usr/lib/python3.8/site-packages/qrexec/policy/parser.py", line 190, in VMTokenMeta
        exacts: collections.OrderedDict[str, Type[str]] = collections.OrderedDict()
    TypeError: 'type' object is not subscriptable

This reverts commit c97b0d71197f1adfa704e2dd5572823d5be3c465.