daemon: add missing brackets in validate_request_id
Fix compile error:

    ../daemon/qrexec-daemon.c:1235:13: error: expected expression
                size_t terminator_offset = i;
                ^
    1 error generated.